### ISSUE TITLE
Fix mobile usability issues

### ISSUE THREAD

**Issue by cherewaty** [thefrontside/frontside.io#42]
Reported by Google Search Console on https://frontside.io/blog/2015/08/14/x-select-status-update.html:
- "Content wider than screen"
- "Clickable elements too close together"

**Comment by taras** [comment]
I think the "Content wider than screen" warning is because of the code block.

<img width="1641" alt="screen shot 2019-03-04 at 11 13 07 am" src="https://user-images.githubusercontent.com/74687/53746140-91813700-3e6e-11e9-86d6-7e68fc743c18.png">

**Comment by taras** [comment]
How can we figure out which items are too close together?
